import { Player, PlayerPosition, PlayerRarity } from "../types/player";
import { assignBaseSkillsFromStats, assignSpecialSkillsFromStats } from "../skills/assignBaseSkills";
import { Difficulty } from "./matchTypes";

const aiPlayer = (id: string, name: string, pos: PlayerPosition, ovr: number, off: number, def: number, rarity: PlayerRarity, img: string, shooting: number, speed: number, strength: number, playmaking: number): Player => ({
  id, name, position: pos, rarity, level: Math.round(ovr / 2), maxLevel: 50, exp: 0, ovr, offense: off, defense: def, imageUrl: img, shooting, speed, strength, playmaking
});

const withAssignedSkills = (roster: Player[]): Player[] =>
  roster.map(p => ({
    ...p,
    baseSkills: p.baseSkills ?? assignBaseSkillsFromStats(p),
    specialSkillSlots: p.specialSkillSlots ?? assignSpecialSkillsFromStats(p),
  }));

const buildAiTeam = (name: string, arena: string, color: string, roster: Player[]) => ({
  name,
  arena,
  color,
  roster: withAssignedSkills(roster),
  off: roster.slice(0, 5).reduce((sum, p) => sum + p.offense, 0),
  def: roster.slice(0, 5).reduce((sum, p) => sum + p.defense, 0),
});

export const mockAiTeams: Record<Difficulty, { name: string; arena: string; off: number; def: number; color: string; roster: Player[] }> = {
  EASY: buildAiTeam('Portland Trail Blazers', 'Moda Center', 'text-green-400', [
    { id: 'por_scoot_henderson', name: 'Scoot Henderson', position: 'PG', rarity: 'Rare', level: 30, maxLevel: 30, exp: 0, ovr: 78, offense: 76, defense: 72, shooting: 68, speed: 90, strength: 62, playmaking: 82, imageUrl: 'https://www.dreamteamph.com/players/newplayers/blazers/scoothenderson.webp' },
    { id: 'por_anfernee_simons', name: 'Anfernee Simons', position: 'SG', rarity: 'Epic', level: 30, maxLevel: 30, exp: 0, ovr: 83, offense: 84, defense: 65, shooting: 86, speed: 82, strength: 52, playmaking: 78, imageUrl: 'https://www.dreamteamph.com/players/newplayers/blazers/anferneesimons.webp' },
    { id: 'por_deni_avdija', name: 'Deni Avdija', position: 'SF', rarity: 'Rare', level: 30, maxLevel: 30, exp: 0, ovr: 80, offense: 80, defense: 82, shooting: 74, speed: 76, strength: 74, playmaking: 72, imageUrl: 'https://www.dreamteamph.com/players/newplayers/blazers/deniavdija.webp' },
    { id: 'por_jerami_grant', name: 'Jerami Grant', position: 'PF', rarity: 'Epic', level: 30, maxLevel: 30, exp: 0, ovr: 82, offense: 82, defense: 76, shooting: 82, speed: 75, strength: 72, playmaking: 68, imageUrl: 'https://www.dreamteamph.com/players/newplayers/blazers/jeramigrant.webp' },
    { id: 'por_deandre_ayton', name: 'Deandre Ayton', position: 'C', rarity: 'Rare', level: 30, maxLevel: 30, exp: 0, ovr: 80, offense: 80, defense: 78, shooting: 62, speed: 68, strength: 82, playmaking: 55, imageUrl: 'https://www.dreamteamph.com/players/newplayers/blazers/deandreayton.webp' },
    { id: 'por_dalano_banton', name: 'Dalano Banton', position: 'PG', rarity: 'Common', level: 30, maxLevel: 30, exp: 0, ovr: 75, offense: 74, defense: 70, shooting: 70, speed: 84, strength: 58, playmaking: 72, imageUrl: 'https://www.dreamteamph.com/players/newplayers/blazers/dalanobanton.webp' },
    { id: 'por_shaedon_sharpe', name: 'Shaedon Sharpe', position: 'SG', rarity: 'Rare', level: 30, maxLevel: 30, exp: 0, ovr: 79, offense: 80, defense: 72, shooting: 76, speed: 85, strength: 60, playmaking: 70, imageUrl: 'https://www.dreamteamph.com/players/newplayers/blazers/shaedonsharpe.webp' },
    { id: 'por_toumani_camara', name: 'Toumani Camara', position: 'SF', rarity: 'Common', level: 30, maxLevel: 30, exp: 0, ovr: 76, offense: 70, defense: 80, shooting: 70, speed: 74, strength: 72, playmaking: 62, imageUrl: 'https://www.dreamteamph.com/players/newplayers/blazers/toumanicamara.webp' },
    { id: 'por_jabari_walker', name: 'Jabari Walker', position: 'PF', rarity: 'Common', level: 30, maxLevel: 30, exp: 0, ovr: 76, offense: 72, defense: 74, shooting: 68, speed: 70, strength: 76, playmaking: 60, imageUrl: 'https://www.dreamteamph.com/players/newplayers/blazers/jabariwalker.webp' },
    { id: 'por_donovan_clingan', name: 'Donovan Clingan', position: 'C', rarity: 'Common', level: 30, maxLevel: 30, exp: 0, ovr: 76, offense: 70, defense: 78, shooting: 50, speed: 58, strength: 84, playmaking: 52, imageUrl: 'https://www.dreamteamph.com/players/newplayers/blazers/donovanclingan.webp' }
  ]),
  NORMAL: buildAiTeam('New York Knicks', 'Madison Square Garden', 'text-dt-cyan', [
    { id: 'nyk_jalen_brunson', name: 'Jalen Brunson', position: 'PG', rarity: 'Legendary', level: 30, maxLevel: 30, exp: 0, ovr: 93, offense: 94, defense: 78, shooting: 90, speed: 85, strength: 64, playmaking: 92, imageUrl: 'https://www.dreamteamph.com/players/newplayers/knicks/jalenbrunson.webp' },
    { id: 'nyk_mikal_bridges', name: 'Mikal Bridges', position: 'SG', rarity: 'Epic', level: 30, maxLevel: 30, exp: 0, ovr: 84, offense: 80, defense: 84, shooting: 82, speed: 78, strength: 65, playmaking: 72, imageUrl: 'https://www.dreamteamph.com/players/newplayers/knicks/mikalbridges.webp' },
    { id: 'nyk_og_anunoby', name: 'OG Anunoby', position: 'SF', rarity: 'Epic', level: 30, maxLevel: 30, exp: 0, ovr: 84, offense: 78, defense: 88, shooting: 80, speed: 76, strength: 75, playmaking: 65, imageUrl: 'https://www.dreamteamph.com/players/newplayers/knicks/oganunoby.webp' },
    { id: 'nyk_karl_anthony_towns', name: 'Karl-Anthony Towns', position: 'PF', rarity: 'Legendary', level: 30, maxLevel: 30, exp: 0, ovr: 89, offense: 90, defense: 76, shooting: 88, speed: 72, strength: 80, playmaking: 70, imageUrl: 'https://www.dreamteamph.com/players/newplayers/knicks/karlanthonytowns.webp' },
    { id: 'nyk_mitchell_robinson', name: 'Mitchell Robinson', position: 'C', rarity: 'Rare', level: 30, maxLevel: 30, exp: 0, ovr: 79, offense: 68, defense: 84, shooting: 40, speed: 64, strength: 86, playmaking: 48, imageUrl: 'https://www.dreamteamph.com/players/newplayers/knicks/mitchellrobinson.webp' },
    { id: 'nyk_cameron_payne', name: 'Cameron Payne', position: 'PG', rarity: 'Common', level: 30, maxLevel: 30, exp: 0, ovr: 75, offense: 75, defense: 68, shooting: 78, speed: 82, strength: 52, playmaking: 76, imageUrl: 'https://www.dreamteamph.com/players/newplayers/knicks/cameronpayne.webp' },
    { id: 'nyk_miles_mcbride', name: 'Miles McBride', position: 'SG', rarity: 'Rare', level: 30, maxLevel: 30, exp: 0, ovr: 77, offense: 76, defense: 76, shooting: 80, speed: 82, strength: 55, playmaking: 70, imageUrl: 'https://www.dreamteamph.com/players/newplayers/knicks/milesmcbride.webp' },
    { id: 'nyk_josh_hart', name: 'Josh Hart', position: 'SF', rarity: 'Epic', level: 30, maxLevel: 30, exp: 0, ovr: 82, offense: 78, defense: 82, shooting: 75, speed: 80, strength: 72, playmaking: 78, imageUrl: 'https://www.dreamteamph.com/players/newplayers/knicks/joshhart.webp' },
    { id: 'nyk_precious_achiuwa', name: 'Precious Achiuwa', position: 'PF', rarity: 'Rare', level: 30, maxLevel: 30, exp: 0, ovr: 77, offense: 74, defense: 76, shooting: 65, speed: 74, strength: 78, playmaking: 58, imageUrl: 'https://www.dreamteamph.com/players/newplayers/knicks/preciousachiuwa.webp' },
    { id: 'nyk_jericho_sims', name: 'Jericho Sims', position: 'C', rarity: 'Common', level: 30, maxLevel: 30, exp: 0, ovr: 73, offense: 64, defense: 74, shooting: 35, speed: 68, strength: 78, playmaking: 45, imageUrl: 'https://www.dreamteamph.com/players/newplayers/knicks/jerichosims.webp' }
  ]),
  HARD: buildAiTeam('Golden State Warriors', 'Chase Center', 'text-dt-gold', [
    { id: 'gsw_stephen_curry', name: 'Stephen Curry', position: 'PG', rarity: 'Mythic', level: 30, maxLevel: 30, exp: 0, ovr: 95, offense: 97, defense: 78, shooting: 99, speed: 85, strength: 60, playmaking: 95, imageUrl: 'https://www.dreamteamph.com/players/newplayers/warriors/stephencurry.webp' },
    { id: 'gsw_brandin_podziemski', name: 'Brandin Podziemski', position: 'SG', rarity: 'Rare', level: 30, maxLevel: 30, exp: 0, ovr: 78, offense: 76, defense: 74, shooting: 78, speed: 78, strength: 62, playmaking: 76, imageUrl: 'https://www.dreamteamph.com/players/newplayers/warriors/brandinpodziemski.webp' },
    { id: 'gsw_andrew_wiggins', name: 'Andrew Wiggins', position: 'SF', rarity: 'Epic', level: 30, maxLevel: 30, exp: 0, ovr: 80, offense: 78, defense: 78, shooting: 78, speed: 80, strength: 70, playmaking: 68, imageUrl: 'https://www.dreamteamph.com/players/newplayers/warriors/andrewwiggins.webp' },
    { id: 'gsw_jonathan_kuminga', name: 'Jonathan Kuminga', position: 'PF', rarity: 'Epic', level: 30, maxLevel: 30, exp: 0, ovr: 80, offense: 80, defense: 74, shooting: 72, speed: 84, strength: 76, playmaking: 68, imageUrl: 'https://www.dreamteamph.com/players/newplayers/warriors/jonathankuminga.webp' },
    { id: 'gsw_trayce_jackson_davis', name: 'Trayce Jackson-Davis', position: 'C', rarity: 'Rare', level: 30, maxLevel: 30, exp: 0, ovr: 78, offense: 68, defense: 78, shooting: 40, speed: 70, strength: 78, playmaking: 62, imageUrl: 'https://www.dreamteamph.com/players/newplayers/warriors/traycejacksondavis.webp' },
    { id: 'gsw_deanthony_melton', name: 'De\'Anthony Melton', position: 'PG', rarity: 'Rare', level: 30, maxLevel: 30, exp: 0, ovr: 78, offense: 75, defense: 78, shooting: 78, speed: 80, strength: 60, playmaking: 72, imageUrl: 'https://www.dreamteamph.com/players/newplayers/warriors/deanthonymelton.webp' },
    { id: 'gsw_buddy_hield', name: 'Buddy Hield', position: 'SG', rarity: 'Epic', level: 30, maxLevel: 30, exp: 0, ovr: 80, offense: 82, defense: 68, shooting: 88, speed: 75, strength: 58, playmaking: 68, imageUrl: 'https://www.dreamteamph.com/players/newplayers/warriors/buddyhield.webp' },
    { id: 'gsw_gary_payton_ii', name: 'Gary Payton II', position: 'SF', rarity: 'Rare', level: 30, maxLevel: 30, exp: 0, ovr: 77, offense: 72, defense: 84, shooting: 70, speed: 82, strength: 65, playmaking: 64, imageUrl: 'https://www.dreamteamph.com/players/newplayers/warriors/garypaytonii.webp' },
    { id: 'gsw_draymond_green', name: 'Draymond Green', position: 'PF', rarity: 'Epic', level: 30, maxLevel: 30, exp: 0, ovr: 81, offense: 74, defense: 86, shooting: 72, speed: 70, strength: 78, playmaking: 84, imageUrl: 'https://www.dreamteamph.com/players/newplayers/warriors/draymondgreen.webp' },
    { id: 'gsw_kevon_looney', name: 'Kevon Looney', position: 'C', rarity: 'Rare', level: 30, maxLevel: 30, exp: 0, ovr: 76, offense: 68, defense: 76, shooting: 40, speed: 58, strength: 80, playmaking: 60, imageUrl: 'https://www.dreamteamph.com/players/newplayers/warriors/kevonlooney.webp' }
  ]),
  EXPERT: buildAiTeam('Boston Celtics', 'TD Garden', 'text-green-500', [
    { id: 'bos_jrue_holiday', name: 'Jrue Holiday', position: 'PG', rarity: 'Epic', level: 30, maxLevel: 30, exp: 0, ovr: 88, offense: 84, defense: 93, shooting: 82, speed: 80, strength: 75, playmaking: 85, imageUrl: 'https://www.dreamteamph.com/players/newplayers/celtics/jrueholiday.webp' },
    { id: 'bos_derrick_white', name: 'Derrick White', position: 'SG', rarity: 'Epic', level: 30, maxLevel: 30, exp: 0, ovr: 88, offense: 85, defense: 89, shooting: 85, speed: 82, strength: 68, playmaking: 82, imageUrl: 'https://www.dreamteamph.com/players/newplayers/celtics/derrickwhite.webp' },
    { id: 'bos_jaylen_brown', name: 'Jaylen Brown', position: 'SF', rarity: 'Legendary', level: 30, maxLevel: 30, exp: 0, ovr: 94, offense: 94, defense: 86, shooting: 88, speed: 86, strength: 82, playmaking: 75, imageUrl: 'https://www.dreamteamph.com/players/newplayers/celtics/jaylenbrown.webp' },
    { id: 'bos_jayson_tatum', name: 'Jayson Tatum', position: 'PF', rarity: 'Legendary', level: 30, maxLevel: 30, exp: 0, ovr: 96, offense: 95, defense: 88, shooting: 92, speed: 82, strength: 80, playmaking: 80, imageUrl: 'https://www.dreamteamph.com/players/newplayers/celtics/jaysontatum.webp' },
    { id: 'bos_kristaps_porzingis', name: 'Kristaps Porzingis', position: 'C', rarity: 'Epic', level: 30, maxLevel: 30, exp: 0, ovr: 88, offense: 88, defense: 84, shooting: 85, speed: 65, strength: 80, playmaking: 60, imageUrl: 'https://www.dreamteamph.com/players/newplayers/celtics/kristapsporzingis.webp' },
    { id: 'bos_al_horford', name: 'Al Horford', position: 'PF', rarity: 'Rare', level: 30, maxLevel: 30, exp: 0, ovr: 82, offense: 78, defense: 84, shooting: 80, speed: 60, strength: 78, playmaking: 70, imageUrl: 'https://www.dreamteamph.com/players/newplayers/celtics/alhorford.webp' },
    { id: 'bos_payton_pritchard', name: 'Payton Pritchard', position: 'PG', rarity: 'Rare', level: 30, maxLevel: 30, exp: 0, ovr: 78, offense: 78, defense: 70, shooting: 82, speed: 84, strength: 52, playmaking: 76, imageUrl: 'https://www.dreamteamph.com/players/newplayers/celtics/paytonpritchard.webp' },
    { id: 'bos_sam_hauser', name: 'Sam Hauser', position: 'SF', rarity: 'Common', level: 30, maxLevel: 30, exp: 0, ovr: 76, offense: 75, defense: 72, shooting: 84, speed: 70, strength: 68, playmaking: 55, imageUrl: 'https://www.dreamteamph.com/players/newplayers/celtics/samhauser.webp' },
    { id: 'bos_luke_kornet', name: 'Luke Kornet', position: 'C', rarity: 'Common', level: 30, maxLevel: 30, exp: 0, ovr: 74, offense: 68, defense: 74, shooting: 40, speed: 55, strength: 78, playmaking: 50, imageUrl: 'https://www.dreamteamph.com/players/newplayers/celtics/lukekornet.webp' },
    { id: 'bos_xavier_tillman', name: 'Xavier Tillman', position: 'PF', rarity: 'Common', level: 30, maxLevel: 30, exp: 0, ovr: 75, offense: 70, defense: 78, shooting: 60, speed: 68, strength: 76, playmaking: 58, imageUrl: 'https://www.dreamteamph.com/players/newplayers/celtics/xaviertillman.webp' }
  ]),
  HELL_EXPERT: buildAiTeam('USA Dream Team', 'Olympic Arena', 'text-dt-red', [
    { id: 'usa_stephen_curry', name: 'Stephen Curry', position: 'PG', rarity: 'Mythic', level: 30, maxLevel: 30, exp: 0, ovr: 99, offense: 99, defense: 88, shooting: 99, speed: 88, strength: 65, playmaking: 96, imageUrl: 'https://www.dreamteamph.com/players/newplayers/warriors/stephencurry.webp' },
    { id: 'usa_devin_booker', name: 'Devin Booker', position: 'SG', rarity: 'Legendary', level: 30, maxLevel: 30, exp: 0, ovr: 94, offense: 95, defense: 80, shooting: 92, speed: 85, strength: 70, playmaking: 84, imageUrl: 'https://www.dreamteamph.com/players/newplayers/suns/devinbooker.webp' },
    { id: 'usa_lebron_james', name: 'LeBron James', position: 'SF', rarity: 'Mythic', level: 30, maxLevel: 30, exp: 0, ovr: 99, offense: 99, defense: 98, shooting: 94, speed: 92, strength: 95, playmaking: 99, imageUrl: 'https://www.dreamteamph.com/players/newplayers/lakers/lebronjames.webp' },
    { id: 'usa_kevin_durant', name: 'Kevin Durant', position: 'PF', rarity: 'Mythic', level: 30, maxLevel: 30, exp: 0, ovr: 99, offense: 99, defense: 92, shooting: 98, speed: 85, strength: 80, playmaking: 88, imageUrl: 'https://www.dreamteamph.com/players/newplayers/suns/kevindurant.webp' },
    { id: 'usa_anthony_davis', name: 'Anthony Davis', position: 'C', rarity: 'Mythic', level: 30, maxLevel: 30, exp: 0, ovr: 98, offense: 96, defense: 99, shooting: 78, speed: 80, strength: 92, playmaking: 70, imageUrl: 'https://www.dreamteamph.com/players/newplayers/lakers/anthonydavis.webp' },
    { id: 'usa_joel_embiid', name: 'Joel Embiid', position: 'C', rarity: 'Legendary', level: 30, maxLevel: 30, exp: 0, ovr: 96, offense: 96, defense: 94, shooting: 82, speed: 70, strength: 95, playmaking: 68, imageUrl: 'https://www.dreamteamph.com/players/newplayers/sixers/joelembiid.webp' },
    { id: 'usa_jayson_tatum', name: 'Jayson Tatum', position: 'SF', rarity: 'Legendary', level: 30, maxLevel: 30, exp: 0, ovr: 96, offense: 95, defense: 88, shooting: 92, speed: 82, strength: 80, playmaking: 80, imageUrl: 'https://www.dreamteamph.com/players/newplayers/celtics/jaysontatum.webp' },
    { id: 'usa_anthony_edwards', name: 'Anthony Edwards', position: 'SG', rarity: 'Legendary', level: 30, maxLevel: 30, exp: 0, ovr: 94, offense: 95, defense: 88, shooting: 88, speed: 92, strength: 82, playmaking: 78, imageUrl: 'https://www.dreamteamph.com/players/newplayers/wolves/anthonyedwards.webp' },
    { id: 'usa_jrue_holiday', name: 'Jrue Holiday', position: 'PG', rarity: 'Epic', level: 30, maxLevel: 30, exp: 0, ovr: 88, offense: 84, defense: 93, shooting: 82, speed: 80, strength: 75, playmaking: 85, imageUrl: 'https://www.dreamteamph.com/players/newplayers/celtics/jrueholiday.webp' },
    { id: 'usa_bam_adebayo', name: 'Bam Adebayo', position: 'C', rarity: 'Epic', level: 30, maxLevel: 30, exp: 0, ovr: 88, offense: 84, defense: 94, shooting: 60, speed: 76, strength: 88, playmaking: 74, imageUrl: 'https://www.dreamteamph.com/players/newplayers/heat/bamadebayo.webp' }
  ]),
  DREAM_TEAM: buildAiTeam('Dream Team', 'Dream Center', 'text-dt-cyan', [
    { id: 'dt_stephen_curry', name: 'Stephen Curry', position: 'PG', rarity: 'Mythic', level: 30, maxLevel: 30, exp: 0, ovr: 96, offense: 97, defense: 78, shooting: 99, speed: 85, strength: 60, playmaking: 95, imageUrl: 'https://www.dreamteamph.com/players/newplayers/warriors/stephencurry.webp' },
    { id: 'dt_shai_gilgeous', name: 'Shai Gilgeous-Alexander', position: 'SG', rarity: 'Mythic', level: 30, maxLevel: 30, exp: 0, ovr: 98, offense: 98, defense: 92, shooting: 90, speed: 88, strength: 68, playmaking: 94, imageUrl: 'https://www.dreamteamph.com/players/newplayers/thunder/shaigilgeousalexander.webp' },
    { id: 'dt_lebron_james', name: 'LeBron James', position: 'SF', rarity: 'Legendary', level: 30, maxLevel: 30, exp: 0, ovr: 91, offense: 92, defense: 88, shooting: 85, speed: 84, strength: 90, playmaking: 90, imageUrl: 'https://www.dreamteamph.com/players/newplayers/lakers/lebronjames.webp' },
    { id: 'dt_giannis_anteto', name: 'Giannis Antetokounmpo', position: 'PF', rarity: 'Mythic', level: 30, maxLevel: 30, exp: 0, ovr: 98, offense: 98, defense: 95, shooting: 70, speed: 88, strength: 92, playmaking: 82, imageUrl: 'https://www.dreamteamph.com/players/newplayers/bucks/giannisantetokounmpo.webp' },
    { id: 'dt_victor_wemby', name: 'Victor Wembanyama', position: 'C', rarity: 'Mythic', level: 30, maxLevel: 30, exp: 0, ovr: 96, offense: 94, defense: 99, shooting: 80, speed: 80, strength: 82, playmaking: 75, imageUrl: 'https://www.dreamteamph.com/players/newplayers/spurs/victorwembanyama.webp' },
    { id: 'dt_anthony_edwards', name: 'Anthony Edwards', position: 'SG', rarity: 'Legendary', level: 30, maxLevel: 30, exp: 0, ovr: 94, offense: 95, defense: 88, shooting: 88, speed: 92, strength: 82, playmaking: 78, imageUrl: 'https://www.dreamteamph.com/players/newplayers/wolves/anthonyedwards.webp' },
    { id: 'dt_anthony_davis', name: 'Anthony Davis', position: 'C', rarity: 'Mythic', level: 30, maxLevel: 30, exp: 0, ovr: 98, offense: 96, defense: 99, shooting: 78, speed: 80, strength: 92, playmaking: 70, imageUrl: 'https://www.dreamteamph.com/players/newplayers/lakers/anthonydavis.webp' },
    { id: 'dt_kevin_durant', name: 'Kevin Durant', position: 'PF', rarity: 'Mythic', level: 30, maxLevel: 30, exp: 0, ovr: 99, offense: 99, defense: 92, shooting: 98, speed: 85, strength: 80, playmaking: 88, imageUrl: 'https://www.dreamteamph.com/players/newplayers/suns/kevindurant.webp' },
    { id: 'dt_luka_doncic', name: 'Luka Doncic', position: 'PG', rarity: 'Mythic', level: 30, maxLevel: 30, exp: 0, ovr: 96, offense: 97, defense: 78, shooting: 90, speed: 78, strength: 80, playmaking: 96, imageUrl: 'https://www.dreamteamph.com/players/newplayers/mavs/lukadoncic.webp' },
    { id: 'dt_nikola_jokic', name: 'Nikola Jokic', position: 'C', rarity: 'Mythic', level: 30, maxLevel: 30, exp: 0, ovr: 97, offense: 97, defense: 82, shooting: 84, speed: 68, strength: 92, playmaking: 98, imageUrl: 'https://www.dreamteamph.com/players/newplayers/nuggets/nikolajokic.webp' }
  ]),
};
