export const STAMINA_CONFIG = {
  movement: {
    normalPerSecond: 0.020,
    randomPerSecond: 0.004,
    fastbreak: 1.50,
    earlyOffense: 1.20,
    fullCourtPress: 1.16,
    overtime: 1.18,
    road: 0.08,
  },
  shooting: {
    openCatchShoot: 2.4,
    normalJumper: 3.8,
    pullUp: 5.2,
    stepBackOrFadeaway: 7.0,
    contestedShot: 6.2,
    heavilyContestedShot: 8.8,
    blockedJumper: 11.5,
  },
  rim: {
    drive: 5.8,
    layup: 7.0,
    dunk: 8.0,
    contactFinish: 10.5,
    blockedLayup: 13.5,
    blockedDunk: 15.5,
    offensiveFoul: 9.0,
  },
  ballHandling: {
    quickTouch: 0.45,
    turnover: 1.85,
    isolation: 2.5,
    lateClockCreation: 2.4,
    doubleTeamEscape: 3.2,
  },
  defense: {
    lightContest: 1.8,
    hardCloseout: 2.8,
    jumpContest: 3.6,
    blockAttempt: 4.8,
    successfulBlock: 5.6,
    failedBlock: 6.4,
    stealAttempt: 4.2,
    successfulSteal: 5.2,
    failedSteal: 7.0,
    pressChase: 1.4,
    trapRotation: 1.8,
    foul: 1.0,
    scoredOnContest: 1.2,
  },
  rebounding: {
    easyRebound: 2.0,
    normalRebound: 2.8,
    contestedRebound: 4.8,
    offensiveReboundBattle: 5.4,
    putbackAttempt: 5.0,
  },
  recovery: {
    benchHomePerTick: 1.5,
    benchAwayPerTick: 1.2,
    timeout: 5,
    quarterBreak: 3,
    halftime: 6,
    overtimeBreak: 8,
    skillSupport: 8,
  },
  modifiers: {
    globalWorkloadScale: 0.74,
    make: 0.82,
    miss: 1.06,
    foul: 0.92,
    block: 1.22,
    heavyContact: 1.18,
    clutchTime: 1.08,
    overtime: 1.18,
    highUsage: 1.08,
    backToBackPossession: 1.08,
    alreadyTired: 1.10,
    exhausted: 1.18,
    transition: 1.12,
    lateClock: 1.12,
    fullCourtPress: 1.12,
    orebSecondChance: 1.10,
  },
} as const;
